### ISSUE TITLE
elive-reconfigure-keyboard-language requires a 'cancel' button

### ISSUE THREAD

**Issue by triantares** [Elive/elive-tools#16]
Like the title says there's need of an 'exit 0' (on a Cancel/Quit button) option on the first 'yes/no' dialog so a user can end the script without touching/changing anything. 
- Any user-started app or script should always offer a clear abort on the first dialog!
Using 'yad' I'd do this (sort of):
```
yad --question --text="$( eval_gettext "Do you want to use the basic and simpler interface instead of the advanced and complete one?" )" --button="Basic"\!gtk-yes:1 --button="Advanced"\!gtk-no --button=gtk-quit:0
```
Currently the script either carries on and starts getting an unwanted '$result' and writing that, before eventually allowing a stop...with unwanted settings.

**Comment by Thanatermesis** [comment]
Mmmh, there's an issue with Yad dialogs where simple widgets doesn't looks "nice" like in zenity, mostly because of the whitespacing used in the body text, we can see them comparing your example with "zenity --question" , I wonder if there's a way to make the body text more "whitespaced" on yad 🤔

**Comment by Thanatermesis** [comment]
@triantares can you betatest it? we need to make sure that changes always work without breaking things :) but especially for the release

**Comment by triantares** [comment]
> Mmmh, there's an issue with Yad dialogs where simple widgets doesn't looks "nice" like in zenity, mostly because of the whitespacing used in the body text, we can see them comparing your example with "zenity --question" , I wonder if there's a way to make the body text more "whitespaced" on yad thinking

There are some simple Markup HTML options/tags directly available.
AFAIK 'yad' uses a monospace font by default but you can change that with '--fontname=' or use tags like <b></b> for Bold.
https://i.imgur.com/Au99MKy.png
I don't use 'zenity' so don't have enough "quick" solutions, hence my 'yad' example. ;)

**Comment by Thanatermesis** [comment]
Mmmh, for complex dialogs "yad" is better than zenity, but for simple ones zenity looks better (this means, can we make yad to look better?), for example looking at your screenshot:

* zenity includes a specific icon for each action that improves the UX (these means: zenity --info, or --question, or --error)
* better whitespaces (we can call them better margins/paddings) in top (around1 line), bottom-to-the-buttons (another line spaced), and to the left a much bigger one

**Comment by triantares** [comment]
> Mmmh, for complex dialogs "yad" is better than zenity, but for simple ones zenity looks better (this means, can we make yad to look better?), for example looking at your screenshot:
> 
>     * zenity includes a specific icon for each action that improves the UX (these means: zenity --info, or --question, or --error)
> 
>     * better whitespaces (we can call them better margins/paddings) in top (around1 line), bottom-to-the-buttons (another line spaced), and to the left a much bigger one

Use "--borders=15" to define a 15 pixel border á volonté. ;)
Use "--image= ......" with path to icon .... or name the specific icon, like:"gtk-dialog-question"

So:
```
yad --question --borders=15 --text="$( eval_gettext "Do you want to use the basic and simpler interface instead of the advanced and complete one?" )" --button="Basic"\!gtk-yes:1 --button="Advanced"\!gtk-no --button=gtk-quit:0 --image="gtk-dialog-question"
```
gives:

https://i.imgur.com/FpD79eE.png

**Comment by triantares** [comment]
I've tested and the quit button works fine.
After opting for 'advanced' it immediately pops up 'gksu' and hitting 'Cancel' pops it up a second time after which a 'Cancel' falls back to 'basic' and 'Cancel' pops up 'gksu' again ...... and after another 'Cancel', I am at last stopped with the unhelpful dialog about writing to system, etc. :cry:

**Comment by Thanatermesis** [comment]
That looks better, I have set a few defaults as you can see on your notifications :)

unfortunately for YAD stills not perfect, the border value only affects to the space between the window-limits and the inside contents, we can see this much more clear if you use --borders=200, see that in zenity the separation is borders but ALSO with the inside contents text, so more exactly we can see that in the separation between the icon and the text, and the text with the buttons

**Comment by triantares** [comment]
> That looks better, I have set a few defaults as you can see on your notifications :)
> 
> unfortunately for YAD stills not perfect, the border value only affects to the space between the window-limits and the inside contents, we can see this much more clear if you use --borders=200, see that in zenity the separation is borders but ALSO with the inside contents text, so more exactly we can see that in the separation between the icon and the text, and the text with the buttons

Yah, given time I'll look those up.
They're all GTK settings anyway.

**Comment by Thanatermesis** [comment]
> Yah, given time I'll look those up.
Maybe in an updated version of YAD they implement it, OR maybe we can request the feature

> They're all GTK settings anyway.
Maybe from a GTK environmental variable 🤔

> It is very unclear how to get a variant like "altGr-intl" for 'US'
Can you repharse "what" is the issue exactly there? :)  btw I think US must always be altgr-featured

**Comment by triantares** [comment]
Latest test fails with
`/elive-reconfigure-language-keyboard: line 33: --on-top: command not found```

**Comment by triantares** [comment]
In the meantime, I found that the 'Quit' button can be added to 'zenity'
With
```--extra-button Quit``

**Comment by triantares** [comment]
For a nicer button layout:
--buttons-layout=spread

(choice is :spread, edge start, end, center)

**Comment by Thanatermesis** [comment]
> Latest test fails with `/elive-reconfigure-language-keyboard: line 33: --on-top: command not found```

Oh! thanks to notice it, that was a very important bug that in no-way should have happened in the release (almost all the gui's in elive will be broken), that's why is not good to change things before doing a release :)

> Remove the $ before yad in line 33 and all is well.

nah, this was correct but was not working :) so "$yad" is a wrapper of the tool with some default options

**Comment by triantares** [comment]
Ah, yes ..... for the 'case ....... esac' $?

BTW,
In the wrapper, the '--button-align=right' is the default setting..... so wont hurt but isn't necessary either.

**Comment by Thanatermesis** [comment]
yes, these zenity warnings are very common, looks like a bug in zenity and happens everywhere

the exit message that shows i think is normal if it does quit correctly

**Comment by triantares** [comment]
On 5/8/23 17:52, Thanatermesis wrote:
> if it does quit correctly

I'm not too sure there.

Just testing the script i.e opting for "basic' or 'advanced' and then hitting all the 'Cancels', still messes up my keymap and sets it to 'en_us" and loses the 'altgr_intl'.

Every time I do anything else other than 'Quit' requires me to run 'setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl' to get my €, ä and é back.

**Comment by Thanatermesis** [comment]
Mmmh, you mean that "configuring correctly the keyboard to english" leads to a non-featured AltGr english? 

I think this is normal (just because it was not set with altgr), but the question here is _"we should **always** set the AltGr for english keyboards?"_ (so, always as default for english). I mean I don't see a reason for not 🤔

Notes:
* use: export EL_DEBUG=3  to see some debug messages of what is doing the tool
* check the resulting file ```/etc/default/keyboard``` where you can see the resulting changes in your configuration (or ```/etc/default/locale``` for the language one)

**Comment by Thanatermesis** [comment]
@triantares I implemented that forced altgr for english keyboards feature and a new package is building now and will upload in 2 minutes, can you try it? not sure if altgr works for Advanced mode or how it should be picked on it (maybe this needs another fix)

**Comment by triantares** [comment]
> Mmmh, you mean that "configuring correctly the keyboard to english" leads to a non-featured AltGr english? 

Yes, where the point actually was that this happens despite me hitting 'Cancel' all the time. That (the changing of the layout) shouldn't be happening at all.

Hitting 'Cancel' should never generate $result, it should abort or exit cleanly.

> yes, these zenity warnings are very common, looks like a bug in zenity and happens everywhere

I've never encountered them elsewhere ...... are you sure this isn't the wrapper, like with 'yad'?

**Comment by triantares** [comment]
I've tested and it looks like us-en and altgr-intl remains intact ..... or keeps on getting put there.
Now I've no way to check anymore other than choosing a different layout like 'de' or 'fr'.

On top 'gxkb' has stopped responding too. :disappointed:

**Comment by triantares** [comment]
Personally I'm not impressed by the 'dpkg-reconfigure' interface as 'advanced' here ....... why do we need it?

**Comment by TheTechRobo** [comment]
@triantares The "simple" one doesn't support variants IIRC, which is a huge problem

**Comment by Thanatermesis** [comment]
> Hitting 'Cancel' should never generate $result, it should abort or exit cleanly.

mmh, which exact dialog (message) is that? i will verify what is doing...

> I've never encountered them elsewhere ...... are you sure this isn't the wrapper, like with 'yad'?

yeah its zenity, im not sure if yad doesn't do it, it happens for example with zenity --question or --entry I think, but in some places like the installer it is run using ```1>/dev/null 2>&1``` to avoid showing them 

> Personally I'm not impressed by the 'dpkg-reconfigure' interface as 'advanced' here ....... why do we need it?

I don't like them much too, "why we need them" ? because they are the defualt way to configure things in debian (debconf system), its ugly yeah, but is the correct one, thats why I don't give it by default this one but the other elive-made one, leaving the debconf one as an option called "advanced" because it includes all possibilities and also are more difficult to use (if you are not a linuxer*, you will not understand these chars).

Yeah as @TheTechRobo said, it includes all the options that the user -may- need

**Comment by Thanatermesis** [comment]
Ok so I assume everything is working now 🤔

**Comment by triantares** [comment]
It works but ..... even for the 'basic' option we should differentiate between the xkb and the system kb, where only the latter needs 'sudo'.
I'm going with the idea that 'basic' actually only needs to be a user choice i.e the xkb option.

**Comment by triantares** [comment]
Strange ..... github takes about 7-8 hours to send an e-mail notification, which puts me off when answering.
Sorry if it looks like double posting.

**Comment by triantares** [comment]
So I'd opt for a 'basic configurator that asks 1. which keymap (chosen system language is irrelevant) is wanted with what variant on what model... nothing else.

The issue is IMO that the commands 'localectl list-x11-keymap-[CHOICE]' where CHOICE is [layouts, models, options, variants] doesn't come up with the specific chosen map variants that "/usr/share/X11/xkb/rules/base.lst" does.
So  'grepping' that file is more useful.

``` sed '/^! variant$/,/^ *$/!d;//d' "/usr/share/X11/xkb/rules/base.lst" | sort -u |grep $result:```
where $result would be the previous map choice.

Just test it by using de, us, fr, es or whatever it works fine. :+1:

**Comment by triantares** [comment]
So I'd opt for a 'basic configurator that asks 1. which keymap (chosen system language is irrelevant) is wanted with what variant on what model... nothing else.

The issue is IMO that the commands 'localectl list-x11-keymap-[CHOICE]' where CHOICE is [layouts, models, options, variants] doesn't come up with the specific chosen map variants that "/usr/share/X11/xkb/rules/base.lst" does.
So  'grepping' that file is more useful.

``` sed '/^! variant$/,/^ *$/!d;//d' "/usr/share/X11/xkb/rules/base.lst" | sort -u |grep $result:```
where $result would be the previous map choice.

Just test it by using de, us, fr, es or whatever it works fine. :+1:

**Comment by Thanatermesis** [comment]
_note that now the languages reconfigurator will pop up with 3 windows questions (language, keyboard, variant), also in live mode_

**Comment by triantares** [comment]
Still some strange stuff going on. :astonished: 

1. I don't get a variant list when choosing 'us', it sets 'altgr_intl' w.o offering others like dvorak, cherokee, euro, macintosh.
2. When, for testing purposes, I opt for German 'de' layout I do get offered 'normal' as variant where there should be about 10 on offer.

There's still a 'Cancel' issue as when, after opting 'de' layout but hitting 'Cancel' on the variant query ..... it goes to 'gksu' (why? It's not needed for 'xkb') and hitting Cancel again ------ leaves me with a German layout. :disappointed:  .... which shouldn't be happening.

**Comment by TheTechRobo** [comment]
@Thanatermesis do it like this. Whenever you make a dialogue box, test out what happens when you cancel. What happens when you close the window? What happens when you OK without selecting anything? Better a bit of extra programming than leaving a bad configuration.

**Comment by Thanatermesis** [comment]
@TheTechRobo it was not tested, that was the point, I didn't had a machine to test and it looked to be a small change, so @triantares  tested it instead since he was checking this keyboard behaviour, in the end the code looked correct but there was more bugs than expected, I finally tested it myself in a vbox to try to catch that last bug 

@triantares I have checked the "cancel" options in the 3 dialogs (select language, keyboard, variant), and I added an exit in the first one (if users hit cancel, configurator exits), but trying to do the same I found that it was already configured for a different behaviour which I think is more optimal, so in short:

1. asks for language: cancel --> exit
2. asks for keyboard, "actual is ES": cancel --> keeps the actual keyboard (ES)
3. asks for variant: cancel --> do not add a variant (except for US-english which will always be altgr-featured)

**Comment by TheTechRobo** [comment]
@Thanatermesis I mean in general though. Please QA your code... otherwise it looks bad for the distro.

**Comment by triantares** [comment]
On 5/10/23 01:43, Thanatermesis wrote:
>
> I found that it was already configured for a different behaviour
>

Yes, that was the whole point .... i thought I noticed that somewhere in 
the script.

> which I think is more optimal, so in short:
>
>  1. asks for language: cancel --> exit
>  2. asks for keyboard, "actual is ES": cancel --> keeps the actual
>     keyboard (ES)
>
It can keep that in memory but shouldn't write to file (yet) if 
canceled, it should exit cleanly w.o touching anything. Even a 'try 
again' is not good .... a user has to be able to leave.


>  1. asks for variant: cancel --> do not add a variant (except for
>     US-english which will always be altgr-featured)
>

I know that there's always a 'point of no return' in a script but, if 
so  ..... then there should be a warning.

I've got a personal yad script for writing/sending invoices (and a lot 
more more) where there is an option to choose/alter existing invoices 
... which, of course is just asking for stupid mistakes so I built in a 
warning and a 'bail out'.

```

### Double check for changing an existing Form.

echo "NR=$NR2 ; SCHIP=$SCHIP2 ; PRODUKT=$PRODUKT2 ; 
LAAD_DATUM=$LAAD_DATUM2 ; CHARTER_NR=$CHARTER ; 
TONNAGE_GELADEN=$TONNAGE_GELADEN2 ; SD=$SD2 ; DSD=$DSD2 ; DST=$DST2 ; 
PLAATS=$PLAATS2 ; XTRA=$XTRA2 ; TOESLAG=$TOESLAG2" > temp-data.txt
[[ -e ~/$(date +%Y)/TXT/$NR2.txt ]] && yad --center --text="File exists, 
Point of no-return now!!" --button="Abort:0" --button="Edit:1"
ret=$?
[[ $ret -eq 0 ]] && exit 0
[[ $ret -eq 1 ]] &&
```

<img src=https://i.imgur.com/71BRpQG.png />

**Comment by triantares** [comment]
And I haven't even started about the 'Back' button not working in the 'advanced' option. :smile:

**Comment by triantares** [comment]
yad --center --text="Keymap will be altered,\n <b>Point of no-return now!!</b>" --button="Abort:0" --button="Edit:1"
ret=$?
[[ $ret -eq 0 ]] && exit 0
[[ $ret -eq 1 ]] &&
```
<img src=https://i.imgur.com/w6tk6yT.png />

BTW, trying out the above directly on the commandline requires the "!!' to be 'escaped' thus: "\!\!" .... else you call a previous command. :fearful: 
Just saying. :smile_cat:

**Comment by Thanatermesis** [comment]
> It can keep that in memory but shouldn't write to file (yet) if canceled, it should exit cleanly w.o touching anything. Even a 'try again' is not good .... a user has to be able to leave.

Note that if this second step (choose keyboard), if it says "keyboard is ES", and user press ESC (which is equal to pressing Cancel), it is like saying "I accept this (or previous) keyboard as ES, I don't want to reconfigure", which in the end there's no difference between "write the conf with the previous conf" and "dont write the conf". I used ESC many times for convenience (and as UX im pretty convinced many other people could do it this way toof

> I know that there's always a 'point of no return' in a script but, if so  ..... then there should be a warning.

As mentioned before, since the Esc behaves like "keeping the previously selected conf" there's no difference between writing and not writing the conf 🤔, so there should be no changes (the only difference is that Cancel doesn't cancel but it keeps the previous conf, for that we should need a third button instead)

> BTW, trying out the above directly on the commandline requires the "!!' to be 'escaped' .... else you call a previous command.

Sounds dangerous :)

Yes as @TheTechRobo says, single quotes doesn't do interpretation of characters, note that it doesn't interpret also variables if you put them on it or translations (variables again)

**Comment by triantares** [comment]
On 5/10/23 15:13, Thanatermesis wrote:
> the only difference is that Cancel doesn't cancel 

That is about the most horrifying UX imaginable.

'Cancel' should be cancel or exit , never but really NEVER anything else.

**Comment by Thanatermesis** [comment]
At the contrary: normally people press ESC when they want to skip a window and not care and don't want to configure anything (which also means, don't configure or pick the default), so ESC (just like Cancel, so its the same thing), does exactly that

Adding a third button will not make sense in the behaviour, how you will name it? and how you will assign it to the Esc key?

Maybe the only problem is that when pressed Esc in the second window it opens the third window, so the correct behaviour should be: "select again 'default' for the third window without showing it up"

**Comment by triantares** [comment]
On 5/10/23 21:27, Thanatermesis wrote:
>
> At the contrary: normally people press ESC when they want to skip a 
> window and not care and don't want to configure anything (which also 
> means, don't configure or pick the default), so ESC (just like Cancel, 
> so its the same thing), does exactly that
>
That is complete bollocks. Escape and Cancel should in all cases exit 
the application cleanly ..... anything else is just completely wrong.


> Adding a third button will not make sense in the behaviour, how you 
> will name it? and how you will assign it to the Esc key?
>
I proposed an 'in-between' warning offering a clean abort and ...... in 
a previous post I've also shown how to add a 3rd button to 'zenity'. 
Just name it 'Quit' or 'Abort' or better yet: Don't use 'Cancel' and 
"OK' where they shouldn't be used in the first place ...... use 'Back' 
and 'Continue'


> Maybe the only problem is that when pressed Esc in the second window 
> it opens the third window, so the correct behaviour should be: "select 
> again 'default' for the third window without showing it up"
>
No, the ONLY problem is that Escape/Cancel is being abused....IMHO it's 
just you not wanting to use other buttons than the default dialog ones 
on 'zenity', even if they're not appropriate.

It is just horrendous UX to come up with your own version of what 
'Cancel' should do. It will eventually come back and bite you, when you 
least expect it to.

**Comment by TheTechRobo** [comment]
Add a "Skip" button and make the cancel button a cancel button.

**Comment by triantares** [comment]
And again:
Asking for the language isn't needed. The only things that matter are the keymap, variant and hardware.
Who cares if a Chinese speaker wants a Swahili keymap ..... it's the keymap that counts. :smiley_cat: 

I've had laptops with German, Swedish, French, Belgian, UK, US and even Dutch keyboards but I always set them to "us altgr-intl" but others who use them after I've 'Elived' them, often can't do blind-typing and want the see what the keys give.

**Comment by Thanatermesis** [comment]
> That is complete bollocks. Escape and Cancel should in all cases exit the application cleanly

So you are saying the same as I'm saying, "exit cleanly", which requires to finish to set the language / keyboard on the system, otherwise you can end up in things like LANG=C

> It is just horrendous UX to come up with your own version of what 'Cancel' should do...

again, "exit cleanly" is not equal to "exit 1", it requires to finish the tool, just, not asking more questions, which is exactly what I have implemented in the last commit

> The only things that matter are the keymap, variant and hardware.
> Who cares if a Chinese speaker wants a Swahili keymap ..... it's the keymap that counts. 

Who cares if the system boots and you found everything in chinese? 🤔 this is what happens when you don't speak the default language included (many people don't speak english), also even if you speak english is an extreme usability to read things in your own language

**Comment by triantares** [comment]
On 5/11/23 00:26, Thanatermesis wrote:
>
>     That is complete bollocks. Escape and Cancel should in all cases
>     exit the application cleanly
>
> So you are saying the same as I'm saying, "exit cleanly", which 
> requires to finish to set the language / keyboard on the system, 
> otherwise you can end up in things like LANG=C
>
No, I'm saying it should stay as the system was before and not touch or 
change anything ...... that's a clean exit.



> again, "exit cleanly" is not equal to "exit 1", it requires to finish 
> the tool, just.
>
Again ... NO!

It shouldn't touch anything and leave it to the user to try again from 
scratch or simply leave everything 'as is'.


> Who cares if the system boots and you found everything in chinese? 🤔 
> this is what happens when you don't speak the default language 
> included (many people don't speak english), also even if you speak 
> english is an extreme usability to read things in your own language
>
I wish you would hold that thought in respect to the language chooser 
that uses previous network connections on the 'live iso'. I really hate 
that! I can just imagine me sitting in a Tokyo hotel connected to their 
wifi, having to decipher Elive popups in Japanese.

Maybe we need a tool to set locales and the language like the 'Advanced' 
option does. This 'basic' app is a 'keyboard-reconfigurator' and useful 
for those that connect a different keyboard or want to fine-tune  ..... 
The system language should be dealt with in a separate tool.

After all, the user already got far enough to find the keyboard tool in 
the running system. The tool the live version uses to change the 
language at boot is quite sufficient for the language. KISS.

**Comment by Thanatermesis** [comment]
> No, I'm saying it should stay as the system was before and not touch or change anything ...... that's a clean exit.

**first**: if the system is not correctly configured, you lead to a broken system
**second**: I repeat: this is EXACTLY what is doing, if you press cancel, it fallbacks to the default / previous configuration

This task is taking me already too many time and everytime it looks more broken while it was correctly working before, I cannot spend more time on this and if I'm not able to work correctly working I will rever all the last changes, there's more prior things and I have already other tasks to finish:

![image](https://github.com/Elive/elive-tools/assets/1181626/518367e2-bcf5-412e-923f-d75f3924a5d7)

> I wish you would hold that thought in respect to the language chooser
> that uses previous network connections on the 'live iso'. I really hate
> that! I can just imagine me sitting in a Tokyo hotel connected to their
> wifi, having to decipher Elive popups in Japanese.

You mean the language selector Elive had in the past before to boot the iso? this was a different boot system, it doesn't exists anymore, and I have implemented a perfect 1:1 replacement which I already **largely debated** in the forum but I think nobody understood that it is the **same** feature

> Maybe we need a tool to set locales and the language like the 'Advanced'
> option does. This 'basic' app is a 'keyboard-reconfigurator' and useful
> for those that connect a different keyboard or want to fine-tune  .....
> The system language should be dealt with in a separate tool.

Maybe, but I'm not going to code that, this is a configurator tool that just works and allows any kind of configuration, languages & keyboard can fit in the same configuration as one depend of the other (if your system boots on chinese, you need to reconfigure both, if does in french, same), the advanced mode does what it suggest, "configure other alternatives if you really need them in an advanced configurator", if you want to code it you will end up in the same tool, a selector of all locales on which will regenerate all locales, so it just uses the default debian tool to configure it like in any other debian (and ubuntu) system, always updated to new changes or locales added so is not even needed to maintain it

> After all, the user already got far enough to find the keyboard tool in
> the running system. The tool the live version uses to change the
> language at boot is quite sufficient for the language. KISS.

I don't understand what you mean here, remember that the Live system always asks for language and keyboard when booting the system so the user should be able to find whatever he wants to search for

**Comment by triantares** [comment]
On 5/11/23 01:02, Thanatermesis wrote:
> I don't understand what you mean here, remember that the Live system 
> always asks for language and keyboard when booting the system so the 
> user should be able to find whatever he wants to search for

Yes, but we're talking about changing the 'keyboard' on an already 
running (installed) system (it's a re-configurator).

I agree that this is taking way too much time but that doesn't change 
the fact that it's not up to the task of letting a user reconfigure the 
keyboard safely.

So I propose we remove it from from the 'elive-ToolCenter/reconfigure' 
app until we have a user oriented one.

**Comment by Thanatermesis** [comment]
_Should work correctly now_

**Comment by triantares** [comment]
We  should take care in how we view this script.
I take "reconfigure" literally as a tool to change an existing keymap whereas you take it as what it originally is: a script to configure a non-existing keymap.
In the latter case, an 'abort' is actually unwanted.
Maybe we indeed need a designated separate reconfigure tool.

**Comment by Thanatermesis** [comment]
> In the latter case, an 'abort' is actually unwanted.
> Maybe we indeed need a designated separate reconfigure tool.

No, it actually supports that, when you press cancel it still uses the previously configured settings

**Comment by triantares** [comment]
On 5/12/23 22:01, Thanatermesis wrote:
>
> No, it actually supports that, when you press cancel it still uses the 
> previously configured settings
>
Yes it does, but it's a stop gap to patch a much too intricate script. I 
think it's about the most newbie alienating app I've ever seen .... even 
M$ does better than that.

Crudely:

What's needed is a simple (non sudo) xkb option.
