### ISSUE TITLE
hitting 'ok' doesn't offer or set 'us' variants.

### ISSUE THREAD

**Issue by triantares** [Elive/elive-tools#19]
Follow up of old issue #16.
to recreate:
1. When changing language (in my case from 'nl' to 'en_US') and 'OK' brings up the next screen.
2. The window states that 'us' is my current keymap so ..... hit 'ok' w.o selecting.

and there's no question about available variants and the keymap is set to simple 'us'.

Maybe a pre-selection might solve that?

**Comment by Thanatermesis** [comment]
Thanks for the detailed bug :) I think the previous commit fixes it (untested), where it preselects the result with the one shown as "actual is..."
