### ISSUE TITLE
Second window of 'reconfigure-keyboard' isn't really searchable.

### ISSUE THREAD

**Issue by triantares** [Elive/elive-tools#20]
The second list that asks the keymap language allows entering charachters for a search but does not apply them to the list.
One has to manually scroll, find and click the language.

**Comment by Thanatermesis** [comment]
_(trying with the first question for keyboard configurator)_ Do you mean typing for example "fr" should preselect the french keyboard ? 🤔 yes it doesn't preselects it. This looks like a bug / limitation on the GUI used (zenity) so we cannot do much here

**Comment by triantares** [comment]
Yes, it sort of starts working but doesn't find anything.
'yad' does do the search correctly in the second (variant) choice list. I just tried that with 'elive-quick-keymap-changer'

**Comment by TheTechRobo** [comment]
I think its because of the spaces before the keymap name though could be wrong. It definitely should work. There's something wrong with the script, not zenity.

**Comment by Thanatermesis** [comment]
good point, fixed
